version: '2'
services:
  webapp:
    restart: always
    build: 
      context: ./web
    labels:
      - "webapp"
    ports:
      - 8080:8080
    links:
      - redis
    volumes:
      - './web/app:/opt/app-root/app'
      #- ./web/logs:/opt/app-root/logs
    command: python app/main.py
#    command: uwsgi --ini /opt/app-root/etc/uwsgi.ini
  postgres:
      image: centos/postgresql-95-centos7
      environment:
        - POSTGRESQL_USER=${POSTGRESQL_USER}
        - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
        - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      ports:
        - 5432:5432
  redis:
      image: redis:latest
