version: '2'
services:
  webapp:
    restart: always
    build: 
      context: ./web
    labels:
      kompose.service.expose: ${HOST}
      io.kompose.service: "webapp"
    links:
      - redis
      - postgresql
    volumes:
      - webapp-logs:/data/logs
      - /opt/app-root/app
    environment:
      - GET_HOSTS_FROM=dns
      #- ./web/app:/opt/app-root/app # Not working. Creating empty directory

  redis:
    image: redis:latest
    labels:
      io.kompose.service: "webapp"

  postgresql:
      image: centos/postgresql-95-centos7
      volumes:
        - postgresql-data:/var/lib/postgresql
      labels:
        io.kompose.service: "webapp"
      environment:
        - POSTGRESQL_USER=${POSTGRESQL_USER}
        - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
        - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      ports:
        - 5432:5432

  nginx:
    build:
      context: ./nginx
    expose:
      - 8080:8080
    volumes_from:
      - web

volumes:
  webapp-logs:
    external: true