version: '2'
services:

  webapp:
    restart: always
    build: 
      context: ./web
    labels:
      io.kompose.service: "webapp"
    ports:
      - 59999:59999
    links:
      - redis
      - postgresql
    volumes:
      - ./web/app:/opt/app-root/app
      - webapp-logs:/logs

  redis:
    image: redis:latest
    labels:
      io.kompose.service: "webapp"

  postgresql:
      image: centos/postgresql-95-centos7
      volumes:
        - /var/lib/postgresql
      labels:
        io.kompose.service: "webapp"
      environment:
        - POSTGRESQL_USER=${POSTGRESQL_USER}
        - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
        - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      ports:
        - 5432:5432

  nginx:
    build:
      context: ./nginx
    labels:
      kompose.service.expose: ${HOST}
      io.kompose.service: "webapp"
    links:
      - webapp
    ports:
      - 8080:8080
    environment:
      - NGINX_HOST=${HOST}
      - NGINX_PORT=8080
    volumes_from:
      - webapp

volumes:
  webapp-logs: {}